<a href="https://colab.research.google.com/github/dhanushkodi45rS/Sales-Performance-Data-Analysis-using-NumPy/blob/main/Data_Analysis_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sales Performance Data Analysis Using NumPy**

In [7]:
import numpy as np
np.random.seed(42)
sales_data = np.random.randint(20, 100, size = (7, 5))

print("Sales Data(product X Days):\n", sales_data)
print("\nShape of the Sales: ", sales_data.shape)
print("\nSize of the Sales: ", sales_data.size)
print("\nDataType of the Sales: ", sales_data.dtype)

total_sales = np.sum(sales_data)
average_sales = np.mean(sales_data)

print("\n\nTotal Sales: ", total_sales)
print("\nAverage Sales: ", average_sales)

product_sales = np.sum(sales_data, axis = 0)
print("\nTotal Sales of the Product Each Day: ", product_sales)

day_sales = np.sum(sales_data, axis = 1)
print("\nSales By Eachday: ", day_sales)

top_index = np.argmax(product_sales)
print("\nTop Product: ", top_index + 1)
print("\nTotal Sales of the Top Product: ", product_sales[top_index])

high_sales_day = day_sales[day_sales > 300]
print("\nDays with over 300 sales: ", high_sales_day)

avg_sales_day = np.mean(sales_data, axis = 1)
print("\nThe average sales of each day: ", np.round(avg_sales_day, 2))

Sales Data(product X Days):
 [[71 34 91 80 40]
 [94 94 43 22 41]
 [72 21 49 57 21]
 [83 79 40 52 95]
 [77 41 68 78 61]
 [79 99 34 81 81]
 [66 81 70 74 83]]

Shape of the Sales:  (7, 5)

Size of the Sales:  35

DataType of the Sales:  int64


Total Sales:  2252

Average Sales:  64.34285714285714

Total Sales of the Product Each Day:  [542 449 395 444 422]

Sales By Eachday:  [316 294 220 349 325 374 374]

Top Product:  1

Total Sales of the Top Product:  542

Days with over 300 sales:  [316 349 325 374 374]

The average sales of each day:  [63.2 58.8 44.  69.8 65.  74.8 74.8]
